apiVersion: v1
kind: ConfigMap
metadata:
  namespace: main-app
  name: pingpong-create-db-cm
data:
  pg_data: "/var/lib/postgresql/data/pgdata"
  seed.sql: |
    CREATE TABLE IF NOT EXISTS pingpong (id SERIAL PRIMARY KEY, pong VARCHAR(16));
  
