apiVersion: v1 # Includes the Service for lazyness
kind: Service
metadata:
  name: postgres-svc
  namespace: main-app
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: postgresapp

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: main-app
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgresapp
  template:
    metadata:
      labels:
        app: postgresapp
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          env:
            - name: PGDATA
              valueFrom:
                # Get Data path from configmap
                configMapKeyRef:
                  name: pingpong-create-db-cm
                  key: pg_data
            - name: POSTGRES_PASSWORD
              valueFrom:
                # Get Postgres Password from secret
                secretKeyRef:
                  name: pingpong-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: db
              containerPort: 5432
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            # Run table creation on init
            - name: pingpong-db-seeding
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pingpong-db-seeding
          configMap:
            name: pingpong-create-db-cm
  volumeClaimTemplates:
    - metadata:
        name: pg-data
        namespace: main-app
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi