FROM node:14

WORKDIR /app

# RUN chown -R -v node:node /app 
# USER node

# Install app dependencies
COPY package*.json ./

RUN npm install

RUN npm ci --only=production

# Bundle app source
COPY generator.js /app/

# Start the app
CMD [ "node" , "generator.js"]