apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main-app
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      # volumes:
      #   - name: shared-image
      #     persistentVolumeClaim:
      #       claimName: image-claim
      containers:
        - name: ping-pong
          image: niklasmtj/ping-pong:latest
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                # Get Postgres Password from secret
                secretKeyRef:
                  name: pingpong-db-secret
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3000
          # volumeMounts: # Mount volume
          # - name: shared-image
          #   mountPath: /app/files