apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main-app
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      # volumes:
      #   - name: shared-image
      #     persistentVolumeClaim:
      #       claimName: image-claim
      containers:
        - name: ping-pong
          image: niklasmtj/ping-pong:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          # volumeMounts: # Mount volume
          # - name: shared-image
          #   mountPath: /app/files