apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: random-string-ingress
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: random-string-svc
          servicePort: 8001
      - path: /pingpong
        backend:
          serviceName: ping-pong-svc
          servicePort: 3001