apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: project-db-secret
  namespace: project-ns
spec:
  encryptedData:
    DATABASE_URL: AgAt/kvpLRXaKS6stHc6QYEHEMlrWi8fP8SvfTqxYRv6zKZ9w5mTuS93iGIr8qmxJG1D+Sl9kRmy6tf93dTBnLDjBoIBWjmCQ/Qk77GY8pTNSVIK1X8C18xorN0L+tcMLwg/dZdjYpUKbuX3ojS3/uMH+RPSpZQ+8F+zpaB5e+QHQLa0O+8ApoWTmg0vq4eCCvJZ1n/ewnoRQQ0qtZatURfH0ozCOffTAL1gYZfuueWEaq+ZDlVO0OFwgudtdND1IbTY2VZxUMbkqvcxFyIkEsyZm7u1HsNP76+t5L4IPc9MQyd5Ni1iDGuJphqR3YPvY+q31N6VEW2X6LMtxbGJGRS6LWHtNGLM8zIOnyLmvURQGBMh5vruRKqFnrQUlX+QeXq3/yu/igRl6KER2dZAuhjExrdtRhVMUgsB8UQM/dYkN+oSsqQXGuHgcQ4bFLKFEURro0i+m3t+YD9PKgdTAqDFfhQPQZ7ZbaPPHXZ96dlolt38kX7Bc8KPTg0rHjBAqXN7w+8ccuhxc6E62ZJyBMg89YMxnYBEOvSNjgAc+HsB6vTeiC4Y2jP78VILHzML7GNzV8UlBLxqJfukYJpbRIW5kvcqCo6Ryp3Pn8kNyhxmjgHluFaMlYFM8jT2Op38JNwQKUssBAYVIp5LkF5Z5FBXB5Wnyvd7OXBRs/1QUi7Fa4eWZeEYtlBts158ppNeiAyVZJVrZ55OMOyY8G7C7CmDd3YJ8jov04XW24olJCZ1tE3JULB6p33991h2HPWNf+fiSM5RVob3k/y9Kh5NW0nFyac=
    POSTGRES_PASSWORD: AgCbw7KU4Dq9+6InE6ypC4k4/t1Xmih54lxHodPDGSwq8Rh+QiIbdyBAiRUDiztUX6XOOzZ8747Qse6WSRxnbImzE+p3ADDzGekrtjFHDa9L8/eLwOYjVd141MthqKiBGXDo5+dLl/vePsXXyZmcpBLVwslCGPEt1u/PPny3CM+J0e0IH7ybEBhy80JyC/Tli/hHw0l+Z8gPtmE6lbd+tLH9+7PgeTa/eWeBjZx6WvSnC45MrLIcQjDdigfYEzOYlfyqZEr3+o8ePfjt7QcVNNoLwuZmCFdrx4Euekcl7b+tPWVNqzGNU7W+t+/J4iMT6A9J+Ev+OF0qgDrfx9eNOqbGBqKPP+BiBChjykd7daNDNapxZg5UBLwV/krDRVQ0hEs1XjrvbE9rCdeOt15scaxyXS6VC/h4TpoMiVm0odeDHlsjQx15FypSgWmXQ/RAKeJ7HWVvg3R74Iq68aosdrFt5aIo/pbAd+JxUtcU32HDHzqEc7P55LGrXXcWQuVOWzjbuAjAWMmd4FEq0lM9sT8uncLsAuP7gee4iWdkggkhgR2eKQKxskXgYjjmPujRY+/OVorz0IrVVIqMjBqwU6yAqHui6kPLa1G/xZqAhpKgIDunsSVhtUNxY6oyqT7sRi0dq2W3CzrByuOSMyzDi4cqri9MUYZ8nsCZrTt9mFMYqcPkd58aIjYBdmlaAjUdQFzP5fc8mtFHMg==
  template:
    metadata:
      creationTimestamp: null
      name: project-db-secret
      namespace: project-ns

