apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: seedimage-ing
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: seedimage-svc
          servicePort: 80