name: Release project application on own branch

on:
  delete:
    branches-ignore:
      - "main"
      - "master"
    paths:
      - "project/**"

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-west3
  BACKEND_IMAGE: devops-project-backend
  FRONTEND_IMAGE: devops-project-frontend

jobs:
  delete-branch-and-namespace:
    name: Delete namespace and deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}
      # - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Delete namespace in Cluster
        working-directory: project
        run: |-
          safe_tag_name=$(sed 's/[^a-zA-Z0-9_]/-/g' <<< ${GITHUB_REF#refs/heads/})
          ./kustomize edit set namespace $safe_tag_name
          kubectl config set-context --current --namespace=$safe_tag_name
          kubectl delete -k .
          kubectl delete namespace $safe_tag_name